FROM maven:3.6.1-jdk-8-alpine

MAINTAINER Elsayed Awd

COPY pom.xml /build/
COPY src /build/src/
COPY sample.db /build/

WORKDIR /build/
RUN mvn clean install

WORKDIR /build/target

ENTRYPOINT ["java", "-jar", "phone-validation-0.0.1-SNAPSHOT.jar"]
