version: '3'

services:
  backendserver:
    build: ./phone-validation-api/
    ports:
             - 8087:5002
    restart: always

  frontend:
    build: ./phone-app/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - 8088:8080
